### ISSUE TITLE
[EPIC] Provide SDK support for new V2 UI

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#1050]
## Problem/Concern

This is an epic that will be used to collect all tasks that need to be completed in order to enable the completion of the new V2 UI.  All of this is part of #820.

- [ ] Default color in palette (first added), can’t be deleted (#979)
- [ ] Figure out how to store and retrieve default colors, as a color palette, from the SDK (#1051)
- [ ] Need to figure out dependencies tree when values changed (#1052)
- [ ] Need to allow the UI to tell the SDK whether it is updating a AA or AAA value (e.g. a shade) (#1053)
- [ ] Need to be able to save multiple themes (#1054)

Any new requirement for the UI should be added here after their respective issues are created.

**Comment by aaronreed708** [comment]
Discussed with @evangk6 today.  We are thinking that a good approach would be:

1. divvy up these issues
- Evan, @omesh-omg  and I will try to figure out #979 together
    - should be a good, isolated issue to get our feet wet with the SDK code
- Evan and I will split the remaining 4, taking 2 each
2. Prepare each issue.  For each issue we need to:
    i. investigate the issue
    ii. resolve all questions, requesting input from Lise, others as needed
    iii. come up with a design, identifying any dependencies that may need to be modified or created
    iv. size the effort
3. Assign the development work
4. Implement the designs

Suggested order of code implementation once investigation and design phase is complete.  This is just a suggestion, but the idea is to unblock Omesh on the UI and to show progress.  To make the largest impact in the shortest amount of time.  But, of course, want to do things in the correct order.

1. Default color in palette (first added), can’t be deleted (#979)
2. Need to be able to save multiple themes (#1054)
3. Need to figure out dependencies tree when values changed (#1052)
4. Need to allow the UI to tell the SDK whether it is updating a AA or AAA value (e.g. a shade) (#1053)
5. Figure out how to store and retrieve default colors, as a color palette, from the SDK (#1051)

Please weigh in if you would like to suggest changes to this path.
