### ISSUE TITLE
09 Nov 2023 - A11y Theme Builder Meeting Minutes

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#714]
## Date
2023/11/09 - 9:15am ET

## Zoom info
- Meeting link: https://zoom.us/j/91013899295?pwd=Qnh5UVN1aUZ4ak9tODgvMVNLNUg5Zz09
- Meeting id: 910 1389 9295
- Password: 123225
- Call-in: +1 929 205 6099 US (New York) (Check calendar for more options)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] [Discuss deprecating previous SDK on NPM](issue #713)
- [x] New community working group update?
- [ ] Cody suggested auto merging updated version PRs (related to #633)
- [x] Suggestions for improvements to prevent inefficient use of contributor time and effort?
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
**New community building working group**
Paula summarized her thoughts on what types of discussion that the working group will have in the near future and what types of activities we might explore to build our community.  She is recruiting Cody and Lise to participate at a minimum.
- Work will be done under #719 

**Discussed deprecating previous NPM module for SDK**
Aaron presented on completion of the code to publish NPM packages of the SDK to FINOS scope in NPM when commits are made to the main branch of the SDK repo.  No contributors on the call were still using the old NPM package.  Aaron suggested that we deprecate the previous package.  There were no dissenting opinions.
- Work will be done under #713

**Help first time contributors**
Aaron brought up some issues that our new contributors are encountering.
- incomplete issues where desired outcomes are not well defined
- contributions begun without talking to issue author
- contributions begun without knowledge of community
    - GitHub notifications can go un-noticed

We discussed how we can make life easier, more efficient for contributors.  It was suggested that perhaps we update the Contributor's guide to:
- encourage new contributors to connect with issue authors before attempting to address an issue
- encourage better issues with more details and proposed outcomes
- encourage new contributors to contact the community to seek out guidance/mentoring on first issue or two in an effort to keep a new contributor from feeling frustrated or discouraged

**Missing CSS Variables**
Alfred discussed observations that he made in #718.  That some CSS variables have spelling errors in their names and other CSS variables are just plain missing.  Alfred is going to start a list so that we have a better idea of where problems might lie.

**Incorrect link**
Alfred noticed an issue in #504 that a link to a piece of documentation was pointing at the previous repo under github.com/discoverfinancial.  Aaron to fix.

**Release process**
We discussed the need for a release process now that releases will be done by publishing the dev branch to main.  One contributor gave some examples of what is done in the Node community.  Juan said that under FINOS that release notes must be made available and FINOS marketing should be notified of releases so what announcements can be made if deemed necessary.  Aaron to open issue to capture these requirements.

## Decisions Made
- [ ] We will deprecate the previous SDKs in NPM
- [ ] ...

## Action Items
- [ ] Aaron to fix link in #504
- [ ] Aaron to open issue for developing a release process
- [ ] Paula to meet with Lise and Cody and brainstorm about Theme Builder community building
- [ ] Aaron to open issue for improving Contributor guide
- [ ] ...

**Comment by turnalfred** [comment]
- [ ] Discuss issue #718 and ways to ensure the variables are valid in the validation of PR's and general Code Quality Checks for the Project itself

**Comment by TheJuanAndOnly99** [comment]
Juan Estrella / FINOS

**Comment by PaulaPaul** [comment]
@PaulaPaul NearForm

**Comment by msdorothyewuah** [comment]
Dorothy Ewuah / Turntabl

**Comment by turnalfred** [comment]
Alfred Neequaye / Turntabl

**Comment by eliblurrtt** [comment]
Elvis Segbawu / Turntabl

**Comment by aaronreed708** [comment]
Aaron Reed/Discover

**Comment by aaronreed708** [comment]
Approved in 11/16 call
