### ISSUE TITLE
30 Nov 2023 - A11y Theme Builder Meeting Minutes

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#736]
## Date
20231130 09:15am EST

## Zoom info
- Meeting link: https://zoom.us/j/91013899295?pwd=Qnh5UVN1aUZ4ak9tODgvMVNLNUg5Zz09
- Meeting id: 910 1389 9295
- Password: 123225
- Call-in: +1 929 205 6099 US (New York) (Check calendar for more options)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Community Working Group update (#678)
- [x] ...
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

- Discussed new landing page, more appealing, informative to attract new community members
    - #678
    - probably more important to have an easily customizable and maintainable website
    - need to improve on what GitHub Pages can give us
    - can we use https://a11y-theme-builder.finos.org/ domain name with a Netlify-deployed website and put docs under a different domain?

- Discussed how our UI could potentially take into account screen readers and render only essential UI so as to distract screen reader users as little as possible (#730)
    - we'd introduce a new mode (e.g. screen reader mode) and our UI would detect when it is active and hide non-essential UI
    - it was suggested that perhaps Arial attributes could be used to hide/ignore elements when screen reader is in use
    - research to be done on most popular screen readers

- Discussed Fluid text adjustments (#732) and what makes it unique
    - @lwnoble brought us up to speed on what Fluid is, that it allows text layout to change as browser window size changes
    - it is thought to be a better approach than the screensize breakpoints (large, tablet, mobile phone) that we currently use
    - please watch the video in #732 to learn more about it

## Decisions Made
- [x] Create design thinking issues to give momentum to #529 and #678

## Action Items
- [x] @aaronreed708  to create Design Thinking issue associated with #529 
- [x] @aaronreed708  to create Design Thinking issue associated with #678
- [ ] @codyzu to look into Aria capabilities and to build a reference list of screen readers

**Comment by evangk6** [comment]
Evan K - DFS

**Comment by codyzu** [comment]
Cody Zuschlag - NearForm

**Comment by PaulaPaul** [comment]
Paula Paul

**Comment by brycecurtis** [comment]
Bryce Curtis - Discover

**Comment by aaronreed708** [comment]
Aaron Reed - Discover
Lise Noble - Discover
Dorothy Ewuah - Turntabl

**Comment by evangk6** [comment]
approved
