### ISSUE TITLE
07 Mar 2024 - A11y Theme Builder Meeting Minutes

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#802]
## Date
2024-03-07 - 09:15am EST

## Zoom info
- Meeting link: https://zoom.us/j/91013899295?pwd=Qnh5UVN1aUZ4ak9tODgvMVNLNUg5Zz09
- Meeting id: 910 1389 9295
- Password: 123225
- Call-in: +1 929 205 6099 US (New York) (Check calendar for more options)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Community working group update (@PaulaPaul)
    - [x] Theme Builder Collaboration Summit - #774  (@PaulaPaul)
    - [x] NPM widget library - #762 (@codyzu)
    - [x] Mind mapping for future presentations - #757 
- [x] CVE Scanning errors - #801 (@aaronreed708)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

- Paula updated us all on last week's Community Working Group call
    - Upcoming conferences, who is doing what abstracts
        - Grace Hopper Open Source Day
        - Grace Hopper Celebration
        - All Things Open
        - OSFF London
- Discussed NPM widget module
    - closest to plug 'n play solution to Material UI users
    - improve ease of getting started with Theme Builder
- Lise discussed needing Keith's help to shore up accessibility calculations in the sdk
- Lise gave update of her discussions with Figma
    - we discussed the possibility of whether a Figma plugin can detect accessibility issues

## Action Items
- [x] Aaron to add epic instructions to developer notes
- [x] Aaron and Lise to discuss and prioritize the "new issue" queue, think about Roadmap
- [x] Paula to get the format required for "bronze" badge from FINOS for DEI
- [x] Aaron to open issue for researching Figma plugin

**Comment by codyzu** [comment]
Cody Zuschlag - Nearform

**Comment by PaulaPaul** [comment]
Paula Paul (@paulapaul) - Greyshore

**Comment by evangk6** [comment]
Evan K - DFS

**Comment by aaronreed708** [comment]
Aaron Reed - DFS
Lise Noble - DFS

**Comment by aaronreed708** [comment]
epic instructions in PR https://github.com/finos/a11y-theme-builder/pull/817

**Comment by aaronreed708** [comment]
Approved in today's meeting.  My Todo's are now Todone's

**Comment by Kayd396** [comment]
Kristen Reed.
