### ISSUE TITLE
14 Mar 2024 - A11y Theme Builder Meeting Minutes

### ISSUE THREAD

**Issue by evangk6** [finos/a11y-theme-builder#810]
## Date
2024-03-14 - 9:15am EST

## Zoom info
- Meeting link: https://zoom.us/j/91013899295?pwd=Qnh5UVN1aUZ4ak9tODgvMVNLNUg5Zz09
- Meeting id: 910 1389 9295
- Password: 123225
- Call-in: +1 929 205 6099 US (New York) (Check calendar for more options)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Update on Aaron
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Check last week's action items
- [ ] Approve past meeting minutes
- [x] Check with Lise how Tuesday's Prioritization went
- [x] Community working group update
- [x] Theme Builder Collaboration Summit update (https://github.com/finos/a11y-theme-builder/issues/774)
- [x] In Progress, High Priority, Triage
- [ ] ...
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- Approve [07 Mar 2024](https://github.com/finos/a11y-theme-builder/issues/802), once Aaron has confirmed his action items
- Community group update: Finos/AnitaB/DFS GAD, London.js, Creating submissions for 4 conferences (Lise and Cody to do two each)
- #797: Yessel will have designs next Wednesday
- #486: waiting on #481
- #544: Lise will reach out to Prithviraj
- #686, #541: Waiting on Turntabl (Paula to reach out to Turntabl)
- SDK: A lot of issues waiting on Keith => Lise found time from Keith, Evan to take simpler issues
- #798: Just needs to be merged by Aaron or Evan
- #762: Revisit this next week
- #774: Meetings are set up
- Aaron to delegate work to Evan where he can
- #731: Assigned to Evan
- #656: Assigned to Evan
- Community Tagged Issues: Moved to in progress, could close next week
- #752: Done but need to open issue to implement it
- #755: Lise to investigate further before handing it off
- #545: Evan to verify if already fixed
- #542: Evan to verify if already fixed
- #503: not needed anymore and closed
- Good First Issues: Ask Aaron if these stay in 'No Status' or whether we should prioritize them
- #664: Need to triage this issue

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items for Next Week
- [x] Approve [07 Mar 2024](https://github.com/finos/a11y-theme-builder/issues/802) minutes when Aaron has reviewed the action items
- [x] Can #481 and #486 be closed?
- [x] Lise will reach out to Prithviraj to check on #544
- [x] Paula will reach out to Turntabl to check their availability (#686, #541)
- [x] Merge #798
- [ ] Revisit Roadmap Issue #762 
- [ ] Aaron to delegate some work to Evan
- [ ] Open issue to implement #752 
- [x] Verify #542 and #545
- [x] Do we triage "Good First Issues"?
- [x] Triage #664

**Comment by lwnoble** [comment]
Lise W Noble

**Comment by evangk6** [comment]
Evan K - DFS

**Comment by codyzu** [comment]
Cody Zuschlag - Nearform

**Comment by PaulaPaul** [comment]
Paula Paul (@PaulaPaul) - Greyshore
