### ISSUE TITLE
04 Apr 2024 - A11y Theme Builder Meeting Minutes

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#819]
## Date
2024-04-04 - 09:15am EDT

## Zoom info
- Meeting link: https://zoom.us/j/91013899295?pwd=Qnh5UVN1aUZ4ak9tODgvMVNLNUg5Zz09
- Meeting id: 910 1389 9295
- Password: 123225
- Call-in: +1 929 205 6099 US (New York) (Check calendar for more options)

## Untracked attendees
- Kristen Reed, student
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Community WG update (@PaulaPaul)
- [x] Epic information added to docs (@aaronreed708)
- [x] Discuss Mentorship polling (@aaronreed708 [[TB] Come up with a good mentorship project](https://github.com/finos/a11y-theme-builder/issues/804))
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

- The meeting started with introductions with a new attendee, Kristen Reed.  She is a student with an interest in Figma.  Welcome Kristen!
- Paula updated us on Turntabl
    - she has reached out to a member of Turntabl, it appears most of their interested contributors have "gone with the wind"
    - we will probably need to re-assign work that was assigned to the Turntabl folks
- Lise updated us on another contributor that has gone silent.  He appears still interested, is also a student.
- Paula updated us on the Community Working Group (which she included in a comment below).
    - We need to put together some educational materials that Summit attendees can peruse prior to the meeting to familiarize themselves with Theme Builder
    - We need to put together some well-defined tasks that could be accomplished during the (roughly) 2 hour summit around:
        - Design
        - SDK
    - James from NatWest (member of FINOS) interested in working with us to create a microsite that tells the FINOS DEI story.  We'd like them to design and create content, we would use Theme Builder to theme the site.
        - Tasks related to microsite perhaps also part of the Summit work
- Lise is looking to share about Theme Builder in a couple of accessibility-themed platforms.  More information in her comment below.
- We discussed that the tie-breaking poll w.r.t. mentorship also ended in a tie!
    - Lise enlightened us with respect to the advantages and disadvantages to both projects, including the commitment of time to research the Figma plugin project and to design and size the effort alone was considerable
    - Due to the fact that the Figma plugin effort could not be easily defined in the near future, we manually broke the tie.  We  determined, with the consensus of all attendees this morning, that the other project (allowing users to update default theme after it has been created) would be the winner

## Decisions Made
- [x] The proposal, "Allow the ability to change color palette and theme after having been defined" will be reflected as the winner of [[TB] Come up with a good mentorship project](https://github.com/finos/a11y-theme-builder/issues/804)

## Action Items
- [x] @lwnoble to update [[REQUEST] Enable LF Badges for Theme Builder contributions](https://github.com/finos/a11y-theme-builder/issues/786) with the latest badge designs from @Chessel
- [x] @lwnoble to speak with Figma about talking about their plugins at Anita B's Open Source Day
- [x] @evangk6 and @aaronreed708 need to build the proposal from the template to discuss on Monday' call with LF and FINOS

**Comment by PaulaPaul** [comment]
Paula Paul - Greyshore (@PaulaPaul )
Community WG updates:
- We have a 'strawman run of show' for the GAAD event at Discover (see comments on https://github.com/finos/a11y-theme-builder/issues/774)
- FINOS would like us to find a way to move the microsite forward, James (NatWest) is interested  in collaborating, can we put some of these pieces together? @PaulaPaul can try to incorporate this into a working session for the community call?
- Lots of abstracts have been submitted!
- Are we ready to go forward with Credly badges? Finalize design selection?

**Comment by lwnoble** [comment]
Lise Noble

**Comment by codyzu** [comment]
Cody Zuschlag - Nearform

**Comment by lwnoble** [comment]
I will be submitting to speak on: https://www.linkedin.com/feed/update/urn:li:activity:7180602693369966592/

Exploring submitting for the Don Norman Award to: https://dnda.design/2024/en/page/home

**Comment by aaronreed708** [comment]
Aaron Reed - DFS

**Comment by Kayd396** [comment]
Hi. It was so nice to meet everyone!

**Comment by kris-reed** [comment]
Kristen Reed

**Comment by aaronreed708** [comment]
Approved in today's meeting.
