### ISSUE TITLE
02 May 2024 - A11y Theme Builder Meeting Minutes

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#845]
## Date
2024-05-02 - 09:15am EDT

## Zoom info
- Meeting link: https://zoom.us/j/91013899295?pwd=Qnh5UVN1aUZ4ak9tODgvMVNLNUg5Zz09
- Meeting id: 910 1389 9295
- Password: 123225
- Call-in: +1 929 205 6099 US (New York) (Check calendar for more options)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- Omesh Kumawat, student
- Apurv Sonawane, student
- Alex Thornton, professional

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Community Update (@PaulaPaul)
- [x] Discuss [Determine approach for maintaining Design assets, and how Designers contribute to the project](https://github.com/finos/a11y-theme-builder/issues/844) (@PaulaPaul)
- [x] Credly badge update (https://github.com/finos/a11y-theme-builder/issues/786) (@PaulaPaul)
- [x] Mentorship Update (@aaronreed708)
- [x] Theme Builder SDK video with Keith (@aaronreed708)
- [x] ...
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- We had 3 new attendees on the call.  Yay!
- Paula is working with FINOS to be part of the Grace Hopper 2024 Open Source Day
    - Where they will have a breakout room to talk about various FINOS technologies
- Lise working with Discover to do another collaboration summit in London
- Paula working with FINOS to figure out how to retain design artifacts used to create FINOS products
    - FINOS would like us to approach Figma to see if they will provide some license deal
    - We will also look at PenPot
        - still need to figure out what to do with the artifacts
- We discussed creating a column in our dashboard for issues we believe will be useful for the Summit
    - We will seed column closer to the Summit
- Lise presented her conclusions from [[TB] Investigate using JSON Tokens in CSS](https://github.com/finos/a11y-theme-builder/issues/760#top) that supports the idea that Theme Builder should only be exporting JSON tokens and that transforms would be used to build other file formats such as CSS.

## Decisions Made
- [ ] ...

## Action Items
- [x] Aaron to create a column in our dashboard for the Summit
- [x] Lise to document her findings in [[TB] Investigate using JSON Tokens in CSS](https://github.com/finos/a11y-theme-builder/issues/760#top

**Comment by codyzu** [comment]
Cody Zuschlag - Nearform

**Comment by Apurv428** [comment]
Apurv Sonawane

**Comment by AThornton24** [comment]
Alex Thornton

**Comment by omesh-omg** [comment]
omesh kumawat

**Comment by aaronreed708** [comment]
Aaron Reed - DFS
Lise Noble - DFS
Paula Paul - Greyshore

**Comment by aaronreed708** [comment]
Approved in today's meeting
